POST https://nodejs-fake-api.herokuapp.com/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###
GET https://nodejs-fake-api.herokuapp.com/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY2OTIwMjM0NCwiZXhwIjoxNjY5MjAzMjQ0fQ.OBBMqxAp0PTMKuWu7OHryHfZLDN3-lY14hgUu_w4SFA